import { Activity, User } from './types'

export const mockActivities: Activity[] = [
  {
    id: '1',
    title: 'Weekend Mountain Trail Ride',
    sportType: 'cycling',
    meetingTime: '2026-03-28T08:00:00',
    meetingLocation: 'Central Park North Gate',
    estimatedDuration: '4 hours',
    maxParticipants: 12,
    currentParticipants: 8,
    itemsToPrep: 'Helmet, water bottle, energy bars, cycling gloves',
    routeFile: 'mountain_trail.gpx',
    organizerPhone: '+1 234 567 8901',
    difficulty: 4,
    organizerId: 'user1',
    organizerName: 'Alex Chen',
    organizerAvatar: '/avatars/alex.jpg',
    createdAt: '2026-03-20T10:00:00',
    participants: ['user1', 'user2', 'user3'],
    photos: [],
    isCompleted: false,
  },
  {
    id: '2',
    title: 'Sunset Beach Hike',
    sportType: 'hiking',
    meetingTime: '2026-03-29T16:00:00',
    meetingLocation: 'Ocean View Parking Lot',
    estimatedDuration: '2.5 hours',
    maxParticipants: 20,
    currentParticipants: 15,
    itemsToPrep: 'Hiking shoes, sunscreen, camera',
    organizerPhone: '+1 345 678 9012',
    difficulty: 2,
    organizerId: 'user2',
    organizerName: 'Sarah Miller',
    organizerAvatar: '/avatars/sarah.jpg',
    createdAt: '2026-03-21T14:00:00',
    participants: ['user1', 'user2'],
    photos: [],
    isCompleted: false,
  },
  {
    id: '3',
    title: 'City Night Cycling Tour',
    sportType: 'cycling',
    meetingTime: '2026-03-30T19:00:00',
    meetingLocation: 'Downtown Plaza',
    estimatedDuration: '3 hours',
    maxParticipants: 15,
    currentParticipants: 10,
    itemsToPrep: 'Bike lights, reflective gear, lock',
    routeFile: 'city_night.gpx',
    organizerPhone: '+1 456 789 0123',
    difficulty: 2,
    organizerId: 'user3',
    organizerName: 'Mike Johnson',
    createdAt: '2026-03-22T09:00:00',
    participants: ['user3'],
    photos: [],
    isCompleted: false,
  },
  {
    id: '4',
    title: 'Forest Trail Adventure',
    sportType: 'hiking',
    meetingTime: '2026-03-15T07:00:00',
    meetingLocation: 'Green Valley Trailhead',
    estimatedDuration: '5 hours',
    maxParticipants: 10,
    currentParticipants: 10,
    itemsToPrep: 'Hiking boots, trekking poles, packed lunch, first aid kit',
    organizerPhone: '+1 567 890 1234',
    difficulty: 5,
    organizerId: 'user1',
    organizerName: 'Alex Chen',
    createdAt: '2026-03-10T08:00:00',
    participants: ['user1', 'user2', 'user3'],
    photos: [
      { id: 'p1', url: '/photos/hike1.jpg', uploadedBy: 'user1', uploadedAt: '2026-03-15T15:00:00' },
      { id: 'p2', url: '/photos/hike2.jpg', uploadedBy: 'user2', uploadedAt: '2026-03-15T15:30:00' },
    ],
    isCompleted: true,
  },
]

export const mockUser: User = {
  id: 'user1',
  name: 'Alex Chen',
  avatar: '/avatars/alex.jpg',
  age: 28,
  gender: 'male',
  preferredSports: ['cycling', 'hiking'],
  joinedActivities: ['1', '2', '4'],
}
